Noop refactor to make MSVC compiler not crash with internal error
MSVC 17.4.5 crashes with internal compilation error when trying to build
RelWithDebInfo:

spring\rts\Game\SelectedUnitsAI.cpp(590): fatal error C1001: Internal compiler error.
(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 224)
 To work around this problem, try simplifying or changing the program near the locations listed above.

so I've rewritten the code a bit to get rid of this issue.